export const SHOP_ACTION_TYPES = {
    REQUEST_LOADING: 'REQUEST_LOADING',
    REQUEST_SUCCESS: 'REQUEST_SUCCESS',
    REQUEST_FAILED: 'REQUEST_FAILED',    
    ADD_SUCCESS: 'ADD_SUCCESS',
    ADD_FAILED: 'ADD_FAILED'
}